name: Test Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6

      - name: Setup build environment
        id: build-env
        uses: ./.
        with:
          branch: 'public'
          steam-user: ${{ secrets.STEAMUSER }}
          steam-password: ${{ secrets.STEAMPASS }}

      - name: Echo resonite environment outputs
        run: |
          echo "Resonite Path: ${{ steps.build-env.outputs.resonite-path }}"
          echo "Resonite Libraries Path: ${{ steps.build-env.outputs.libraries-path }}"
